### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Columbam1998** [J-onasJones/YetAnotherDiscordChatLink#1]
hello I'm getting a crash using the following mods 
![image](https://github.com/J-onasJones/YetAnotherDiscordChatLink/assets/36681633/9dd19fc8-0eec-4aa6-90a6-6f1dc8a15390)

here's the log
[2023-11-14-2.log](https://github.com/J-onasJones/YetAnotherDiscordChatLink/files/13349258/2023-11-14-2.log)

Hope it helps!

**Comment by JonasunderscoreJones** [comment]
Fixed in version `1.1.1` [commit](https://github.com/J-onasJones/YetAnotherDiscordChatLink/commit/a74e5bd4b074d910961a8bb864f5672c578ae51b)
